triple-store:
  # (!) SPARQL endpoint to store data 
  # Change this only if you want to use other triple store or different than "crf" repository
  sparql-endpoint: http://agraph:10035/repositories/crf/statements
  auth:
    # (!) Change accordingly to your allegrograph/agraph.cfg
    username: admin
    password: password
  graph:
    named: true
    type: http://purl.org/vodan/whocovid19crfsemdatamodel/who-covid-19-rapid-crf

fdp:
  token: a274793046e34a219fd0ea6362fcca61a001500b71724f4c973a017031653c20
  # (!) Insert UUID of distribution created in FAIR Data Point related to CRFs data
  # Until the following line is commented, metadata in FDP won't be updated when CRF is submitted
  # distribution: http://fdp_client/distribution/<distribution_uuid>
